from tau2.utils.utils import DATA_DIR

KNOWLEDGE_CONFLICT_DATA_DIR = DATA_DIR / "tau2" / "domains" / "knowledge_conflict"
KNOWLEDGE_CONFLICT_DB_PATH = KNOWLEDGE_CONFLICT_DATA_DIR / "db.json"
KNOWLEDGE_CONFLICT_POLICY_PATH = KNOWLEDGE_CONFLICT_DATA_DIR / "policy.md"
KNOWLEDGE_CONFLICT_TASK_SET_PATH = KNOWLEDGE_CONFLICT_DATA_DIR / "tasks.json"
