from tau2.utils.utils import DATA_DIR

PERSONALASSISTANT_DATA_DIR = DATA_DIR / "tau2" / "domains" / "personalAssistant"
PERSONALASSISTANT_DB_PATH = PERSONALASSISTANT_DATA_DIR / "db.json"
PERSONALASSISTANT_POLICY_PATH = PERSONALASSISTANT_DATA_DIR / "policy.md"
PERSONALASSISTANT_TASK_SET_PATH = PERSONALASSISTANT_DATA_DIR / "tasks.json"