model_list:
  - model_name: Qwen/Qwen35B
    litellm_params:
      model: openai/Qwen/Qwen35B
      api_base: http://localhost:8000/v1
      timeout: 3600
      api_key: local-testing
      # 重点：在这里注入禁用思考模式的参数
      extra_body:
        chat_template_kwargs:
          enable_thinking: false
